"""estrutura_entradas_compras

Revision ID: 202eeb37a619
Revises: a8b2d7afa8cf
Create Date: 2026-07-14 15:50:18.814538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202eeb37a619'
down_revision: Union[str, Sequence[str], None] = 'a8b2d7afa8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.Integer(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('nota_fiscal', sa.String(), nullable=True),
    sa.Column('chave_nfe', sa.String(), nullable=True),
    sa.Column('lancamento_fiscal', sa.String(), nullable=True),
    sa.Column('processo_entrada', sa.String(), nullable=True),
    sa.Column('tipo_movimento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entradas_id'), 'entradas', ['id'], unique=False)
    op.create_table('itens_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('custo_nota', sa.Float(), nullable=True),
    sa.Column('aliquota_icms', sa.Float(), nullable=True),
    sa.Column('aliquota_ipi', sa.Float(), nullable=True),
    sa.Column('descricao_produto', sa.String(), nullable=True),
    sa.Column('condicao_pagamento', sa.String(), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('tipo_embalagem', sa.String(), nullable=True),
    sa.Column('bonificacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_entrada_id'), 'itens_entrada', ['id'], unique=False)
   # op.drop_constraint(op.f('produtos_fornecedor_id_fkey'), 'produtos', type_='foreignkey')
   # op.drop_column('produtos', 'fornecedor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('produtos_fornecedor_id_fkey'), 'produtos', 'fornecedores', ['fornecedor_id'], ['id'])
    op.drop_index(op.f('ix_itens_entrada_id'), table_name='itens_entrada')
    op.drop_table('itens_entrada')
    op.drop_index(op.f('ix_entradas_id'), table_name='entradas')
    op.drop_table('entradas')
    # ### end Alembic commands ###
