"""cria tabela vendas

Revision ID: 4c2b5efea499
Revises: e693fdce3853
Create Date: 2026-07-22 11:03:20.639673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2b5efea499'
down_revision: Union[str, Sequence[str], None] = 'e693fdce3853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('codigo_produto', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('quantidade_embalagem', sa.Float(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('custo_total', sa.Float(), nullable=True),
    sa.Column('margem', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_codigo_produto'), 'vendas', ['codigo_produto'], unique=False)
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_codigo_produto'), table_name='vendas')
    op.drop_table('vendas')
    # ### end Alembic commands ###
