"""cria tabela departamentos

Revision ID: 56356308b6e6
Revises: af5e70f4af5c
Create Date: 2026-08-03 09:46:08.254341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56356308b6e6'
down_revision: Union[str, Sequence[str], None] = 'af5e70f4af5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamentos_codigo'), 'departamentos', ['codigo'], unique=True)
    op.create_index(op.f('ix_departamentos_id'), 'departamentos', ['id'], unique=False)
    op.alter_column('produtos', 'departamento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'departamento',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_departamentos_id'), table_name='departamentos')
    op.drop_index(op.f('ix_departamentos_codigo'), table_name='departamentos')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
