"""ajusta tabela vendas

Revision ID: 66b0a54eec0f
Revises: 4c2b5efea499
Create Date: 2026-07-22 11:20:10.553561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b0a54eec0f'
down_revision: Union[str, Sequence[str], None] = '4c2b5efea499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('qtde_embalagem', sa.Numeric(precision=12, scale=3), nullable=True))
    op.alter_column('vendas', 'quantidade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
    op.alter_column('vendas', 'valor_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=True)
    op.alter_column('vendas', 'valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('vendas', 'custo_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=True)
    op.alter_column('vendas', 'custo_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('vendas', 'margem',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_vendas_data'), 'vendas', ['data'], unique=False)
    op.create_index(op.f('ix_vendas_empresa'), 'vendas', ['empresa'], unique=False)
    op.drop_column('vendas', 'quantidade_embalagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('quantidade_embalagem', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vendas_empresa'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_data'), table_name='vendas')
    op.alter_column('vendas', 'margem',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vendas', 'custo_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vendas', 'custo_unitario',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vendas', 'valor_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vendas', 'valor_unitario',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vendas', 'quantidade',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('vendas', 'qtde_embalagem')
    # ### end Alembic commands ###
