"""cria configuracao dos tipos de alertas

Revision ID: 804091f2096d
Revises: f6c08d4eabde
Create Date: 2026-08-28 13:23:30.115112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804091f2096d'
down_revision: Union[str, Sequence[str], None] = 'f6c08d4eabde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_tipos_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('alteracao_preco', sa.Boolean(), nullable=False),
    sa.Column('estoque_minimo', sa.Boolean(), nullable=False),
    sa.Column('sem_movimentacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_tipos_alertas_id'), 'config_tipos_alertas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_tipos_alertas_id'), table_name='config_tipos_alertas')
    op.drop_table('config_tipos_alertas')
    # ### end Alembic commands ###
