"""estrutura_inicial

Revision ID: a8b2d7afa8cf
Revises: 
Create Date: 2026-07-14 15:29:26.263164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b2d7afa8cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_table('historico_importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('arquivo', sa.String(length=200), nullable=False),
    sa.Column('registros', sa.Integer(), nullable=True),
    sa.Column('inseridos', sa.Integer(), nullable=True),
    sa.Column('atualizados', sa.Integer(), nullable=True),
    sa.Column('erros', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_importacao_id'), 'historico_importacao', ['id'], unique=False)
    op.create_table('perfis_importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfis_importacao_id'), 'perfis_importacao', ['id'], unique=False)
    op.create_table('mapeamentos_importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=50), nullable=False),
    sa.Column('coluna', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis_importacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapeamentos_importacao_id'), 'mapeamentos_importacao', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estoque', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_mapeamentos_importacao_id'), table_name='mapeamentos_importacao')
    op.drop_table('mapeamentos_importacao')
    op.drop_index(op.f('ix_perfis_importacao_id'), table_name='perfis_importacao')
    op.drop_table('perfis_importacao')
    op.drop_index(op.f('ix_historico_importacao_id'), table_name='historico_importacao')
    op.drop_table('historico_importacao')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
