"""adiciona departamento_id em produtos

Revision ID: d1627198f285
Revises: 56356308b6e6
Create Date: 2026-08-03 14:36:16.326457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1627198f285'
down_revision: Union[str, Sequence[str], None] = '56356308b6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('departamento_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_produtos_departamento_id'), 'produtos', ['departamento_id'], unique=False)
    op.create_foreign_key(None, 'produtos', 'departamentos', ['departamento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_index(op.f('ix_produtos_departamento_id'), table_name='produtos')
    op.drop_column('produtos', 'departamento_id')
    # ### end Alembic commands ###
