"""ajuste_relacionamentos_produtos

Revision ID: e693fdce3853
Revises: 685f166206e6
Create Date: 2026-07-14 16:37:41.606951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e693fdce3853'
down_revision: Union[str, Sequence[str], None] = '685f166206e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_entrada', 'aliquota_ipi')
    op.drop_column('itens_entrada', 'aliquota_icms')
    op.drop_column('produtos', 'fornecedor_principal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('fornecedor_principal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('produtos_fornecedor_id_fkey'), 'produtos', 'fornecedores', ['fornecedor_principal_id'], ['id'])
    op.add_column('itens_entrada', sa.Column('aliquota_icms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('itens_entrada', sa.Column('aliquota_ipi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
